[package]
name = "input-record"
version = "0.1.0"
authors = ["Christopher Chin <ctchin13@gmail.com>"]

[dependencies]
input = { path = "/home/yutoo/input.rs" }
libudev-sys = "*"
libc = "*"
time = "*"
