/// Keys and buttons
///
/// Most of the keys/buttons are modeled after USB HUT 1.12
/// (see http://www.usb.org/developers/hidpage).
/// Also see linux/include/uapi/linux/input-event-codes.h
///
/// Abbreviations in the comments:
/// AC - Application Control
/// AL - Application Launch Button
/// SC - System Contro
///
#[repr(u8)]
#[derive(Copy, Clone, Debug)]
pub enum Key {
    Reserved,
    Esc,
    One,
    Two,
    Three,
    Four,
    Five,
    Six,
    Seven,
    Eight,
    Nine,
    Zero,
    Minus,
    Equal,
    Backspace,
    Tab,
    Q,
    W,
    E,
    R,
    T,
    Y,
    U,
    I,
    O,
    P,
    LeftBrace,
    RightBrace,
    Enter,
    LeftCtrl,
    A,
    S,
    D,
    F,
    G,
    H,
    J,
    K,
    L,
    Semicolon,
    Apostrophe,
    Grave,
    LeftShift,
    BackSlash,
    Z,
    X,
    C,
    V,
    B,
    N,
    M,
    Comma,
    Dot,
    Slash,
    RightShift,
    Kpasterisk,
    LeftAlt,
    Space,
    CapsLock,
    F1,
    F2,
    F3,
    F4,
    F5,
    F6,
    F7,
    F8,
    F9,
    F10,
    NumLock,
    ScrollLock,
    Kp7,
    Kp8,
    Kp9,
    Kpminus,
    Kp4,
    Kp5,
    Kp6,
    Kpplus,
    Kp1,
    Kp2,
    Kp3,
    Kp0,
    Kpdot,

    Zenkakuhankaku,
    PoundDisplaced, // 102nd key
    F11,
    F12,
    Ro,
    Katakana,
    Hiragana,
    Henkan,
    Katakanahiragana,
    Muhenkan,
    Kpjpcomma,
    Kpenter,
    RightCtrl,
    Kpslash,
    Sysrq,
    RightAlt,
    LineFeed,
    Home,
    Up,
    PageUp,
    Left,
    Right,
    End,
    Down,
    PageDown,
    Insert,
    Delete,
    Macro,
    Mute,
    VolumeDown,
    VolumeUp,
    Power,	/* sc system power down */
    Kpequal,
    Kpplusminus,
    Pause,
    Scale,  /* al compiz scale (expose) */

    Kpcomma,
    Hangeul,
    Hanguel,
    Hanja,
    Yen,
    LeftMeta,
    RightMeta,
    Compose,

    Stop,  /* ac stop */
    Again,
    Props,  /* ac properties */
    Undo,  /* ac undo */
    Front,
    Copy,  /* ac copy */
    Open,  /* ac open */
    Paste,  /* ac paste */
    Find,  /* ac search */
    Cut,  /* ac cut */
    Help,  /* al integrated help center */
    Menu,  /* menu (show menu) */
    Calc,  /* al calculator */
    Setup,
    Sleep,  /* sc system sleep */
    Wakeup,  /* system wake up */
    File,  /* al local machine browser */
    SendFile,
    DeleteFile,
    Xfer,
    Prog1,
    Prog2,
    Www,  /* al internet browser */
    Msdos,
    Coffee,  /* al terminal lock/screensaver */
    //screenlock,  coffee
    RotateDisplay,  /* display orientation for e.g. tablets */
    //direction,  rotate_display
    CycleWindows,
    Mail,
    Bookmarks,  /* ac bookmarks */
    Computer,
    Back,  /* ac back */
    Forward,  /* ac forward */
    CloseCD,
    EjectCD,
    EjectCloseCD,
    NextSong,
    PlayPause,
    PreviousSong,
    StopCD,
    Record,
    Rewind,
    Phone,  /* media select telephone */
    Iso,
    Config,  /* al consumer control configuration */
    Homepage,  /* ac home */
    Refresh,  /* ac refresh */
    Exit,  /* ac exit */
    Move,
    Edit,
    ScrollUp,
    ScrollDown,
    Kpleftparen,
    Kprightparen,
    New,  /* ac new */
    Redo,  /* ac redo/repeat */

    F13,
    F14,
    F15,
    F16,
    F17,
    F18,
    F19,
    F20,
    F21,
    F22,
    F23,
    F24,

    PlayCD,
    PauseCD,
    Prog3,
    Prog4,
    Dashboard,  /* al dashboard */
    Suspend,
    Close,  /* ac close */
    Play,
    FastForward,
    BassBoost,
    Print,  /* ac print */
    Hp,
    Camera,
    Sound,
    Question,
    Email,
    Chat,
    Search,
    Connect,
    Finance,  /* al checkbook/finance */
    Sport,
    Shop,
    Alterase,
    Cancel,  /* ac cancel */
    BrightnessDown,
    BrightnessUp,
    Media,

    SwitchVideoMode,  /* cycle between available video
					   outputs (Monitor/LCD/TV-out/etc) */
    Kbdillumtoggle,
    Kbdillumdown,
    Kbdillumup,

    Send,  /* ac send */
    Reply,  /* ac reply */
    ForwardMail,  /* ac forward msg */
    Save,  /* ac save */
    Documents,

    Battery,

    BlueTooth,
    Wlan,
    Uwb,

    Unknown,

    VideoNext,  /* drive next video source */
    VideoPrev,  /* drive previous video source */
    BrightnessCycle,  /* brightness up, after max is min */
    BrightnessAuto,  /* set auto brightness: manual brightness control is off, rely on ambient */
    DisplayOff,  /* display device to off state */

    Wwan,  /* wireless wan (lte, umts, gsm, etc.) */
//#define WIMAX		KEY_WWAN
    RFkill,  /* key that controls all radios */

    MicMute,  /* mute / unmute the microphone */
}

impl From<Key> for u8 {
    fn from(val: Key) -> u8 {
        match val {
            Key::Reserved => 0,
            Key::Esc => 1,
            Key::One => 2,
            Key::Two => 3,
            Key::Three => 4,
            Key::Four => 5,
            Key::Five => 6,
            Key::Six => 7,
            Key::Seven => 8,
            Key::Eight => 9,
            Key::Nine => 10,
            Key::Zero => 11,
            Key::Minus => 12,
            Key::Equal => 13,
            Key::Backspace => 14,
            Key::Tab => 15,
            Key::Q => 16,
            Key::W => 17,
            Key::E => 18,
            Key::R => 19,
            Key::T => 20,
            Key::Y => 21,
            Key::U => 22,
            Key::I => 23,
            Key::O => 24,
            Key::P => 25,
            Key::LeftBrace => 26,
            Key::RightBrace => 27,
            Key::Enter => 28,
            Key::LeftCtrl => 29,
            Key::A => 30,
            Key::S => 31,
            Key::D => 32,
            Key::F => 33,
            Key::G => 34,
            Key::H => 35,
            Key::J => 36,
            Key::K => 37,
            Key::L => 38,
            Key::Semicolon => 39,
            Key::Apostrophe => 40,
            Key::Grave => 41,
            Key::LeftShift => 42,
            Key::BackSlash => 43,
            Key::Z => 44,
            Key::X => 45,
            Key::C => 46,
            Key::V => 47,
            Key::B => 48,
            Key::N => 49,
            Key::M => 50,
            Key::Comma => 51,
            Key::Dot => 52,
            Key::Slash => 53,
            Key::RightShift => 54,
            Key::Kpasterisk => 55,
            Key::LeftAlt => 56,
            Key::Space => 57,
            Key::CapsLock => 58,
            Key::F1 => 59,
            Key::F2 => 60,
            Key::F3 => 61,
            Key::F4 => 62,
            Key::F5 => 63,
            Key::F6 => 64,
            Key::F7 => 65,
            Key::F8 => 66,
            Key::F9 => 67,
            Key::F10 => 68,
            Key::NumLock => 69,
            Key::ScrollLock => 70,
            Key::Kp7 => 71,
            Key::Kp8 => 72,
            Key::Kp9 => 73,
            Key::Kpminus => 74,
            Key::Kp4 => 75,
            Key::Kp5 => 76,
            Key::Kp6 => 77,
            Key::Kpplus => 78,
            Key::Kp1 => 79,
            Key::Kp2 => 80,
            Key::Kp3 => 81,
            Key::Kp0 => 82,
            Key::Kpdot => 83,
            Key::Zenkakuhankaku => 84,
            Key::PoundDisplaced => 85,
            Key::F11 => 86,
            Key::F12 => 87,
            Key::Ro => 88,
            Key::Katakana => 89,
            Key::Hiragana => 90,
            Key::Henkan => 91,
            Key::Katakanahiragana => 92,
            Key::Muhenkan => 93,
            Key::Kpjpcomma => 94,
            Key::Kpenter => 95,
            Key::RightCtrl => 96,
            Key::Kpslash => 97,
            Key::Sysrq => 98,
            Key::RightAlt => 99,
            Key::LineFeed => 100,
            Key::Home => 101,
            Key::Up => 102,
            Key::PageUp => 103,
            Key::Left => 104,
            Key::Right => 105,
            Key::End => 106,
            Key::Down => 107,
            Key::PageDown => 108,
            Key::Insert => 109,
            Key::Delete => 110,
            Key::Macro => 111,
            Key::Mute => 112,
            Key::VolumeDown => 113,
            Key::VolumeUp => 114,
            Key::Power => 115,
            Key::Kpequal => 116,
            Key::Kpplusminus => 117,
            Key::Pause => 118,
            Key::Scale => 119,
            Key::Kpcomma => 120,
            Key::Hangeul => 121,
            Key::Hanguel => 122,
            Key::Hanja => 123,
            Key::Yen => 124,
            Key::LeftMeta => 125,
            Key::RightMeta => 126,
            Key::Compose => 127,
            Key::Stop => 128,
            Key::Again => 129,
            Key::Props => 130,
            Key::Undo => 131,
            Key::Front => 132,
            Key::Copy => 133,
            Key::Open => 134,
            Key::Paste => 135,
            Key::Find => 136,
            Key::Cut => 137,
            Key::Help => 138,
            Key::Menu => 139,
            Key::Calc => 140,
            Key::Setup => 141,
            Key::Sleep => 142,
            Key::Wakeup => 143,
            Key::File => 144,
            Key::SendFile => 145,
            Key::DeleteFile => 146,
            Key::Xfer => 147,
            Key::Prog1 => 148,
            Key::Prog2 => 149,
            Key::Www => 150,
            Key::Msdos => 151,
            Key::Coffee => 152,
            Key::RotateDisplay => 153,
            Key::CycleWindows => 154,
            Key::Mail => 155,
            Key::Bookmarks => 156,
            Key::Computer => 157,
            Key::Back => 158,
            Key::Forward => 159,
            Key::CloseCD => 160,
            Key::EjectCD => 161,
            Key::EjectCloseCD => 162,
            Key::NextSong => 163,
            Key::PlayPause => 164,
            Key::PreviousSong => 165,
            Key::StopCD => 166,
            Key::Record => 167,
            Key::Rewind => 168,
            Key::Phone => 169,
            Key::Iso => 170,
            Key::Config => 171,
            Key::Homepage => 172,
            Key::Refresh => 173,
            Key::Exit => 174,
            Key::Move => 175,
            Key::Edit => 176,
            Key::ScrollUp => 177,
            Key::ScrollDown => 178,
            Key::Kpleftparen => 179,
            Key::Kprightparen => 180,
            Key::New => 181,
            Key::Redo => 182,
            Key::F13 => 183,
            Key::F14 => 184,
            Key::F15 => 185,
            Key::F16 => 186,
            Key::F17 => 187,
            Key::F18 => 188,
            Key::F19 => 189,
            Key::F20 => 190,
            Key::F21 => 191,
            Key::F22 => 192,
            Key::F23 => 193,
            Key::F24 => 194,
            Key::PlayCD => 200,
            Key::PauseCD => 201,
            Key::Prog3 => 202,
            Key::Prog4 => 203,
            Key::Dashboard => 204,
            Key::Suspend => 205,
            Key::Close => 206,
            Key::Play => 207,
            Key::FastForward => 208,
            Key::BassBoost => 209,
            Key::Print => 210,
            Key::Hp => 211,
            Key::Camera => 212,
            Key::Sound => 213,
            Key::Question => 214,
            Key::Email => 215,
            Key::Chat => 216,
            Key::Search => 217,
            Key::Connect => 218,
            Key::Finance => 219,
            Key::Sport => 220,
            Key::Shop => 221,
            Key::Alterase => 222,
            Key::Cancel => 223,
            Key::BrightnessDown => 224,
            Key::BrightnessUp => 225,
            Key::Media => 226,
            Key::SwitchVideoMode => 227,
            Key::Kbdillumtoggle => 228,
            Key::Kbdillumdown => 229,
            Key::Kbdillumup => 230,
            Key::Send => 231,
            Key::Reply => 232,
            Key::ForwardMail => 233,
            Key::Save => 234,
            Key::Documents => 235,
            Key::Battery => 236,
            Key::BlueTooth => 237,
            Key::Wlan => 238,
            Key::Uwb => 239,
            Key::Unknown => 240,
            Key::VideoNext => 241,
            Key::VideoPrev => 242,
            Key::BrightnessCycle => 243,
            Key::BrightnessAuto => 244,
            Key::DisplayOff => 245,
            Key::Wwan => 246,
            Key::RFkill => 247,
            Key::MicMute => 248,
        }
    }
}

impl From<u8> for Key {
    fn from(val: u8) -> Key {
        match val {
            0 => Key::Reserved,
            1 => Key::Esc,
            2 => Key::One,
            3 => Key::Two,
            4 => Key::Three,
            5 => Key::Four,
            6 => Key::Five,
            7 => Key::Six,
            8 => Key::Seven,
            9 => Key::Eight,
            10 => Key::Nine,
            11 => Key::Zero,
            12 => Key::Minus,
            13 => Key::Equal,
            14 => Key::Backspace,
            15 => Key::Tab,
            16 => Key::Q,
            17 => Key::W,
            18 => Key::E,
            19 => Key::R,
            20 => Key::T,
            21 => Key::Y,
            22 => Key::U,
            23 => Key::I,
            24 => Key::O,
            25 => Key::P,
            26 => Key::LeftBrace,
            27 => Key::RightBrace,
            28 => Key::Enter,
            29 => Key::LeftCtrl,
            30 => Key::A,
            31 => Key::S,
            32 => Key::D,
            33 => Key::F,
            34 => Key::G,
            35 => Key::H,
            36 => Key::J,
            37 => Key::K,
            38 => Key::L,
            39 => Key::Semicolon,
            40 => Key::Apostrophe,
            41 => Key::Grave,
            42 => Key::LeftShift,
            43 => Key::BackSlash,
            44 => Key::Z,
            45 => Key::X,
            46 => Key::C,
            47 => Key::V,
            48 => Key::B,
            49 => Key::N,
            50 => Key::M,
            51 => Key::Comma,
            52 => Key::Dot,
            53 => Key::Slash,
            54 => Key::RightShift,
            55 => Key::Kpasterisk,
            56 => Key::LeftAlt,
            57 => Key::Space,
            58 => Key::CapsLock,
            59 => Key::F1,
            60 => Key::F2,
            61 => Key::F3,
            62 => Key::F4,
            63 => Key::F5,
            64 => Key::F6,
            65 => Key::F7,
            66 => Key::F8,
            67 => Key::F9,
            68 => Key::F10,
            69 => Key::NumLock,
            70 => Key::ScrollLock,
            71 => Key::Kp7,
            72 => Key::Kp8,
            73 => Key::Kp9,
            74 => Key::Kpminus,
            75 => Key::Kp4,
            76 => Key::Kp5,
            77 => Key::Kp6,
            78 => Key::Kpplus,
            79 => Key::Kp1,
            80 => Key::Kp2,
            81 => Key::Kp3,
            82 => Key::Kp0,
            83 => Key::Kpdot,
            84 => Key::Zenkakuhankaku,
            85 => Key::PoundDisplaced,
            86 => Key::F11,
            87 => Key::F12,
            88 => Key::Ro,
            89 => Key::Katakana,
            90 => Key::Hiragana,
            91 => Key::Henkan,
            92 => Key::Katakanahiragana,
            93 => Key::Muhenkan,
            94 => Key::Kpjpcomma,
            95 => Key::Kpenter,
            96 => Key::RightCtrl,
            97 => Key::Kpslash,
            98 => Key::Sysrq,
            99 => Key::RightAlt,
            100 => Key::LineFeed,
            101 => Key::Home,
            102 => Key::Up,
            103 => Key::PageUp,
            104 => Key::Left,
            105 => Key::Right,
            106 => Key::End,
            107 => Key::Down,
            108 => Key::PageDown,
            109 => Key::Insert,
            110 => Key::Delete,
            111 => Key::Macro,
            112 => Key::Mute,
            113 => Key::VolumeDown,
            114 => Key::VolumeUp,
            115 => Key::Power,
            116 => Key::Kpequal,
            117 => Key::Kpplusminus,
            118 => Key::Pause,
            119 => Key::Scale,
            120 => Key::Kpcomma,
            121 => Key::Hangeul,
            122 => Key::Hanguel,
            123 => Key::Hanja,
            124 => Key::Yen,
            125 => Key::LeftMeta,
            126 => Key::RightMeta,
            127 => Key::Compose,
            128 => Key::Stop,
            129 => Key::Again,
            130 => Key::Props,
            131 => Key::Undo,
            132 => Key::Front,
            133 => Key::Copy,
            134 => Key::Open,
            135 => Key::Paste,
            136 => Key::Find,
            137 => Key::Cut,
            138 => Key::Help,
            139 => Key::Menu,
            140 => Key::Calc,
            141 => Key::Setup,
            142 => Key::Sleep,
            143 => Key::Wakeup,
            144 => Key::File,
            145 => Key::SendFile,
            146 => Key::DeleteFile,
            147 => Key::Xfer,
            148 => Key::Prog1,
            149 => Key::Prog2,
            150 => Key::Www,
            151 => Key::Msdos,
            152 => Key::Coffee,
            153 => Key::RotateDisplay,
            154 => Key::CycleWindows,
            155 => Key::Mail,
            156 => Key::Bookmarks,
            157 => Key::Computer,
            158 => Key::Back,
            159 => Key::Forward,
            160 => Key::CloseCD,
            161 => Key::EjectCD,
            162 => Key::EjectCloseCD,
            163 => Key::NextSong,
            164 => Key::PlayPause,
            165 => Key::PreviousSong,
            166 => Key::StopCD,
            167 => Key::Record,
            168 => Key::Rewind,
            169 => Key::Phone,
            170 => Key::Iso,
            171 => Key::Config,
            172 => Key::Homepage,
            173 => Key::Refresh,
            174 => Key::Exit,
            175 => Key::Move,
            176 => Key::Edit,
            177 => Key::ScrollUp,
            178 => Key::ScrollDown,
            179 => Key::Kpleftparen,
            180 => Key::Kprightparen,
            181 => Key::New,
            182 => Key::Redo,
            183 => Key::F13,
            184 => Key::F14,
            185 => Key::F15,
            186 => Key::F16,
            187 => Key::F17,
            188 => Key::F18,
            189 => Key::F19,
            190 => Key::F20,
            191 => Key::F21,
            192 => Key::F22,
            193 => Key::F23,
            194 => Key::F24,
            200 => Key::PlayCD,
            201 => Key::PauseCD,
            202 => Key::Prog3,
            203 => Key::Prog4,
            204 => Key::Dashboard,
            205 => Key::Suspend,
            206 => Key::Close,
            207 => Key::Play,
            208 => Key::FastForward,
            209 => Key::BassBoost,
            210 => Key::Print,
            211 => Key::Hp,
            212 => Key::Camera,
            213 => Key::Sound,
            214 => Key::Question,
            215 => Key::Email,
            216 => Key::Chat,
            217 => Key::Search,
            218 => Key::Connect,
            219 => Key::Finance,
            220 => Key::Sport,
            221 => Key::Shop,
            222 => Key::Alterase,
            223 => Key::Cancel,
            224 => Key::BrightnessDown,
            225 => Key::BrightnessUp,
            226 => Key::Media,
            227 => Key::SwitchVideoMode,
            228 => Key::Kbdillumtoggle,
            229 => Key::Kbdillumdown,
            230 => Key::Kbdillumup,
            231 => Key::Send,
            232 => Key::Reply,
            233 => Key::ForwardMail,
            234 => Key::Save,
            235 => Key::Documents,
            236 => Key::Battery,
            237 => Key::BlueTooth,
            238 => Key::Wlan,
            239 => Key::Uwb,
            240 => Key::Unknown,
            241 => Key::VideoNext,
            242 => Key::VideoPrev,
            243 => Key::BrightnessCycle,
            244 => Key::BrightnessAuto,
            245 => Key::DisplayOff,
            246 => Key::Wwan,
            247 => Key::RFkill,
            248 => Key::MicMute,
            _ => panic!("Key from u8 failed."),
        }
    }
}
